export const dummyUsers = [
  {
    id: 1,
    name: "Kasun Chiwantha",
    dob: "1998-04-29",
    sex: 0,
    image: "default.png",
    state: 1,
  },
  {
    id: 2,
    name: "Ravindu Jayasuriya",
    dob: "1999-02-18",
    sex: 0,
    image: "default.png",
    state: 1,
  },
  {
    id: 3,
    name: "Nadeesha Perera",
    dob: "2001-11-23",
    sex: 1,
    image: "default.png",
    state: 1,
  },
  {
    id: 4,
    name: "Tharindu Silva",
    dob: "1997-05-10",
    sex: 0,
    image: "default.png",
    state: 1,
  },
  {
    id: 5,
    name: "Sajini Fernando",
    dob: "2000-09-14",
    sex: 1,
    image: "default.png",
    state: 1,
  },
  {
    id: 6,
    name: "Amal Gunawardena",
    dob: "1996-12-04",
    sex: 0,
    image: "default.png",
    state: 1,
  },
  {
    id: 7,
    name: "Chathuri Ranasinghe",
    dob: "1998-08-22",
    sex: 1,
    image: "default.png",
    state: 1,
  },
  {
    id: 8,
    name: "Pasindu Madushan",
    dob: "1999-03-16",
    sex: 0,
    image: "default.png",
    state: 1,
  },
  {
    id: 9,
    name: "Dilini Weerasinghe",
    dob: "2000-10-01",
    sex: 1,
    image: "default.png",
    state: 1,
  },
  {
    id: 10,
    name: "Supun Jayawardena",
    dob: "1995-06-27",
    sex: 0,
    image: "default.png",
    state: 1,
  },
  {
    id: 11,
    name: "Harini Dissanayake",
    dob: "1999-01-11",
    sex: 1,
    image: "default.png",
    state: 1,
  },
  {
    id: 12,
    name: "Isuru Bandara",
    dob: "1997-07-19",
    sex: 0,
    image: "default.png",
    state: 1,
  },
  {
    id: 13,
    name: "Rashmi Ekanayake",
    dob: "2001-05-30",
    sex: 1,
    image: "default.png",
    state: 1,
  },
  {
    id: 14,
    name: "Thilan Karunaratne",
    dob: "1998-02-09",
    sex: 0,
    image: "default.png",
    state: 1,
  },
  {
    id: 15,
    name: "Piumi Senanayake",
    dob: "1999-12-25",
    sex: 1,
    image: "default.png",
    state: 1,
  },
  {
    id: 16,
    name: "Sahan Liyanage",
    dob: "1996-10-13",
    sex: 0,
    image: "default.png",
    state: 1,
  },
  {
    id: 17,
    name: "Maneesha Perera",
    dob: "2000-08-02",
    sex: 1,
    image: "default.png",
    state: 1,
  },
  {
    id: 18,
    name: "Niroshan Peiris",
    dob: "1997-03-07",
    sex: 0,
    image: "default.png",
    state: 1,
  },
  {
    id: 19,
    name: "Sanduni Jayalath",
    dob: "2001-09-18",
    sex: 1,
    image: "default.png",
    state: 1,
  },
  {
    id: 20,
    name: "Dulanjana Silva",
    dob: "1998-11-06",
    sex: 0,
    image: "default.png",
    state: 1,
  },
];
